#数据目录
app:
  data-dir: ./data
#Https及http端口配置，server.port 是tomcat默认端口参数必须配置，server.http.port 是http端口
#server.https.port是https端口
#debug: true
server:
  port: 8090
  http:
    port: 8090
  https:
    port: 8043

  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  #Https 证书配置
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    servlet:
      load-on-startup: 1
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
    async:
      request-timeout: 30000
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
logging:
  file:
    name: logs/service.log
  level:
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %msg%n'
    dateformat: 'yyyy-MM-dd HH:mm:ss'
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 50MB
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  #    joda-date-time-format: yyyy-MM-dd HH:mm:ss
web:
  resources:
    static-locations: classpath:/static/

mybatis-plus:
  #  mapper-locations: classpath:/mapper/*.xml logging.config=classpath:log4j2.xml
  mapper-locations: classpath:/mapper/*.xml,classpath*:/dao/*.xml
  type-handlers-package: com.example.typehandler
  type-enums-package: com.example.utils.enums
  configuration:
    map-underscore-to-camel-case: true
